export const ADD_BOOKS_FROM_QUERY = "ADD_BOOKS_FROM_QUERY";
export const MOVE_TO_CURRENTLY_READING = "MOVE_TO_CURRENTLY_READING";
export const MOVE_TO_WANT_TO_READ = "MOVE_TO_WANT_TO_READ";
export const MOVE_TO_READ = "MOVE_TO_READ";
export const REMOVE_FROM_MY_BOOKS = "REMOVE_FROM_MY_BOOKS";
